version: "3.8"

services:
    mysql-server:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=kang9396
        ports:
            - "3306:3306"

    myredis:
        image: redis:6.2
        ports:
            - "6379:6379"
    